### ISSUE TITLE
同じ予定名が複数ある時まとめて表示したい

### ISSUE THREAD

**Issue by Ryota0312** [Ryota0312/mkrecord#4]
講義カレンダを読み込むと同じ講義がいっぱいでてくるので，
それらをまとめて下のようにしたい．

```
+ データ構造とアルゴリズム (XX/XX, YY/YY, ZZ/ZZ)```

**Comment by kjtbw** [comment]
10d688b133f76df14f9f51b0910c20b0720dbac3 にて，作業を行なった．

## 今後の課題
+ EventCollectionの，parseメソッドを実装する．
    + 現在は，すべてSingleEventとして分類する従来のparseしかできていない．今後は，以下の処理流れで，SIngleEvent とRipitainEventを作成したい．
    1. EventCollection.parseにて，google_eventsを，eventのsummaryでsortする．
    2. 1でsortしたものをなめて，summaryが変わっているところで，切り分け，同じ名前のeventがかたまったlistを作成する．
    3. 2で作ったlistについて，SingleEventかRipitaitionEventを作成する．
